name: Create Draft

on:
  issues:
    types: [opened, edited, deleted, labeled, unlabeled, closed]
  push:
    branches:
      - main

permissions:
  issues: read
  contents: write
jobs:
  create_draft:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'
          cache-dependency-path: 'actions/create-draft/yarn.lock'
      - name: Create Draft
        run: |
          yarn install
          yarn run create-draft
        working-directory: actions/create-draft
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${GITHUB_REPOSITORY}
          GIT_COMMIT_SHA: ${{ github.sha }}
          DRAFT_LABEL: "Status: Draft"
