name: On Release

on:
  release:
    types: [released, edited]
permissions:
  issues: write
  contents: read
jobs:
  on_release:
    runs-on: ubuntu-18.04
    if: ${{ github.event.release.draft == false }}
    steps:
      - name: dump context
        run: echo '${{ toJSON(github) }}'
      - name: checkout
        uses: actions/checkout@v2
      - name: setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: 'yarn'
          cache-dependency-path: 'actions/create-draft/yarn.lock'
      - name: Create Draft
        run: |
          yarn install
          yarn run on-release
        working-directory: actions/create-draft
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
          GITHUB_REPOSITORY: ${GITHUB_REPOSITORY}
          RELEASED_TAG_NAME: ${{ github.event.release.tag_name }}
          RELEASED_LABEL: "Status: Released"
